"""cambio

Revision ID: 9ab107b2a0f2
Revises: acf284a52e5f
Create Date: 2016-05-19 09:38:09.892704

"""

# revision identifiers, used by Alembic.
revision = '9ab107b2a0f2'
down_revision = 'acf284a52e5f'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('skills', sa.Column('logo', sa.Unicode(length=255), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('skills', 'logo')
    ### end Alembic commands ###
