"""modificacion

Revision ID: d146f2dbb7e0
Revises: 70c5db251d28
Create Date: 2016-05-20 17:21:28.337291

"""

# revision identifiers, used by Alembic.
revision = 'd146f2dbb7e0'
down_revision = '70c5db251d28'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('site', sa.Unicode(length=255), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('companies', 'site')
    ### end Alembic commands ###
